
sudo: required

language: cpp

os:
    - linux

compiler:
    - gcc

addons:
    apt:
        packages:
            - libreadline6 
            - libreadline6-dev

branches:
    only:
        - master

before_install:
    - gcc --version
    - g++ --version

script:
    - make -j2

